<?php
declare(strict_types=1);

/**
 * Read-only access to Claude Code's own JSONL conversation transcripts
 * under ~/.claude/projects/<encoded-cwd>/<session-id>.jsonl - this file
 * never writes to them. Sessions created via create_cc_session() are
 * launched with an explicit --session-id (a UUID this app generates
 * itself, stored in the sidecar - see generate_uuid_v4() in Sessions.php),
 * so a transcript is found by globbing for that UUID's filename rather
 * than reimplementing Claude Code's own cwd -> directory-name encoding.
 */

function claude_projects_dir(): string
{
    return home_root() . '/.claude/projects';
}

/**
 * JSONL line types that carry no `message` payload (mode switches,
 * permission-mode changes, bridge/queue bookkeeping, file-history
 * snapshots, stop-hook summaries, ...) - skipped when rendering history.
 * Verified against a real, 700+-message transcript that none of these
 * (nor any other observed type) ever carry a `message` key, so
 * parse_transcript_line()'s own `!is_array($message)` check would filter
 * them out regardless - this list exists for clarity/intent, not as the
 * only thing standing between them and getting rendered as garbage.
 *
 * @return string[]
 */
function transcript_meta_only_types(): array
{
    return [
        'mode', 'permission-mode', 'bridge-session', 'last-prompt', 'attachment', 'ai-title',
        'system', 'queue-operation', 'file-history-snapshot', 'file-history-delta',
    ];
}

/**
 * Finds the transcript file for a session id generated by
 * generate_uuid_v4() - never trusts $claudeSessionId to already be safe,
 * since it ultimately traces back to a sidecar file, so it's validated as
 * UUID-shaped before touching the filesystem.
 */
function find_transcript_path(string $claudeSessionId): ?string
{
    if (preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i', $claudeSessionId) !== 1) {
        return null;
    }

    $matches = glob(claude_projects_dir() . '/*/' . $claudeSessionId . '.jsonl') ?: [];

    return $matches[0] ?? null;
}

// A hard safety cap, not a display preview length - the UI already collapses
// blocks by default (see render_collapsible_block() in AgentClient.php), so
// this only exists to stop a truly pathological single block (e.g. a huge
// file dump) from bloating the page. Expanding a block should show it in
// full for any normal-sized command/tool output.
const TRANSCRIPT_BLOCK_HARD_CAP_LENGTH = 50000;

/**
 * Field names (checked in this order) that hold a tool_use's single most
 * useful argument to show for the tool actually invoked, e.g. `command`
 * for Bash, `file_path` for Read/Edit/Write, `pattern` for Grep/Glob -
 * mirrors the "ToolName(argument)" convention Claude Code's own TUI uses
 * (verified against a real capture: "Bash(echo ... > /tmp/...)"). `element`
 * covers MCP browser-automation tools (verified against a real capture of
 * an MCP Playwright browser_click call: {"element": "...", "target": "..."}).
 *
 * @return string[]
 */
function tool_use_primary_arg_keys(): array
{
    return ['command', 'file_path', 'pattern', 'query', 'url', 'path', 'prompt', 'element', 'description'];
}

/**
 * MCP tool names come through as "mcp__<server>__<tool>" - reformatted to
 * "server.tool" (e.g. "mcp__playwright__browser_click" ->
 * "playwright.browser_click"), matching how the server groups its tools,
 * without the noisy double-underscore prefix. Returns the name unchanged
 * for anything that isn't MCP-shaped.
 */
function humanize_tool_name(string $name): string
{
    if (preg_match('/^mcp__([^_]+(?:_[^_]+)*)__(.+)$/', $name, $m) === 1) {
        return $m[1] . '.' . $m[2];
    }

    return $name;
}

/**
 * AskUserQuestion's input has no single scalar "primary" argument (it's a
 * nested questions/options structure), so it would otherwise fall through
 * to summarize_tool_use()'s raw-JSON-dump fallback - unreadable, and often
 * cut off mid-structure by the block-length hard cap. This turns it into
 * "question (option / option); question2 (...)" instead, matching what a
 * human actually wants to see: what was asked and what the choices were.
 *
 * @param array<string, mixed> $input
 */
function summarize_ask_user_question(array $input): ?string
{
    $questions = $input['questions'] ?? null;

    if (!is_array($questions) || $questions === []) {
        return null;
    }

    $parts = [];

    foreach ($questions as $q) {
        if (!is_array($q)) {
            continue;
        }

        $question = is_string($q['question'] ?? null) ? $q['question'] : '';
        $options = is_array($q['options'] ?? null) ? $q['options'] : [];
        $labels = [];

        foreach ($options as $opt) {
            if (is_array($opt) && is_string($opt['label'] ?? null) && $opt['label'] !== '') {
                $labels[] = $opt['label'];
            }
        }

        if ($question === '' && $labels === []) {
            continue;
        }

        $parts[] = trim($question . ($labels !== [] ? ' (' . implode(' / ', $labels) . ')' : ''));
    }

    return $parts !== [] ? implode('; ', $parts) : null;
}

// Matches collapsible_summary()'s own single-line threshold (the
// downstream render_collapsible_block()/renderCollapsibleBlock() rule
// that skips the expand affordance entirely for trivial content) - the
// decision has to be made here, not there, since once this returns a
// multi-line string, the downstream renderer has no way to know it could
// have fit on one line.
const TOOL_USE_SUMMARY_LINE_MAX = 80;

/**
 * @param array<string, mixed> $input
 * @return string[] "key: value" lines, the primary arg (see
 *   tool_use_primary_arg_keys()) first if present, then every other
 *   param in $input's own order - unlike the single-primary-arg-only
 *   format this replaced, nothing is dropped. Non-scalar values are
 *   JSON-encoded compactly rather than skipped.
 */
function tool_use_param_lines(array $input): array
{
    $primaryKey = null;

    foreach (tool_use_primary_arg_keys() as $key) {
        if (array_key_exists($key, $input)) {
            $primaryKey = $key;
            break;
        }
    }

    $lines = [];

    if ($primaryKey !== null) {
        $lines[] = tool_use_param_line($primaryKey, $input[$primaryKey]);
    }

    foreach ($input as $key => $value) {
        if ($key === $primaryKey) {
            continue;
        }

        $lines[] = tool_use_param_line((string)$key, $value);
    }

    return $lines;
}

function tool_use_param_line(string $key, mixed $value): string
{
    if (is_scalar($value)) {
        return "{$key}: {$value}";
    }

    $json = json_encode($value);

    return "{$key}: " . ($json !== false ? $json : '(unrepresentable)');
}

/**
 * "tool: X" plus every param, e.g. "tool: Bash - command: pwd" - joined
 * onto one line for a short/simple call (mirrors the existing
 * trivial-block rule: no point in an expand affordance for something
 * already fully visible), broken out into its own "Params:" list
 * otherwise, one "- key: value" per line.
 *
 * @param string[] $paramLines
 */
function format_tool_use_summary(string $displayName, array $paramLines): string
{
    if ($paramLines === []) {
        return "tool: {$displayName}";
    }

    $singleLine = "tool: {$displayName} - " . implode(', ', $paramLines);

    if (!str_contains($singleLine, "\n") && mb_strlen($singleLine) <= TOOL_USE_SUMMARY_LINE_MAX) {
        return $singleLine;
    }

    $bulleted = array_map(static fn(string $line): string => "- {$line}", $paramLines);

    return "tool: {$displayName}\nParams:\n" . implode("\n", $bulleted);
}

/**
 * "tool: X - key: value, ..." (or the multi-line "Params:" form for
 * anything long enough to need it - see format_tool_use_summary()) - not
 * just the bare tool name, so a Bash entry shows the actual command run,
 * an Edit shows the file touched, etc., instead of requiring a click into
 * `tool_result` to guess what happened. Shows every param, not just one
 * primary argument.
 */
function summarize_tool_use(array $block): string
{
    $name = (string)($block['name'] ?? 'tool');
    $displayName = humanize_tool_name($name);
    $input = $block['input'] ?? null;

    if (!is_array($input) || $input === []) {
        return "tool: {$displayName}";
    }

    if ($name === 'AskUserQuestion') {
        $summary = summarize_ask_user_question($input);

        if ($summary !== null) {
            return format_tool_use_summary($displayName, [$summary]);
        }
    }

    return format_tool_use_summary($displayName, tool_use_param_lines($input));
}

/**
 * @param array<string, mixed> $block
 * @return array{kind:string, text:string}
 */
function summarize_content_block(array $block): array
{
    $type = (string)($block['type'] ?? '');

    return match ($type) {
        'text' => ['kind' => 'text', 'text' => (string)($block['text'] ?? '')],
        'tool_use' => ['kind' => 'tool_use', 'text' => summarize_tool_use($block)],
        'tool_result' => array_filter(
            [
                'kind' => 'tool_result',
                'text' => transcript_tool_result_text($block['content'] ?? null),
                'image' => transcript_tool_result_image($block['content'] ?? null),
            ],
            static fn(mixed $v): bool => $v !== null
        ),
        'image' => transcript_image_from_block($block) !== null
            ? ['kind' => 'image', 'text' => '', 'image' => transcript_image_from_block($block)]
            : ['kind' => 'image', 'text' => '(image could not be displayed)'],
        default => ['kind' => $type !== '' ? $type : 'unknown', 'text' => ''],
    };
}

/**
 * A tool_result's `content` is either a plain string or a list of blocks
 * (usually just {type: "text", text: ...}) - flattened to plain text for
 * the history view, which only ever shows a preview, never the raw shape.
 */
function transcript_tool_result_text(mixed $content): string
{
    if (is_string($content)) {
        return $content;
    }

    if (!is_array($content)) {
        return '';
    }

    $parts = [];

    foreach ($content as $item) {
        if (is_array($item) && ($item['type'] ?? null) === 'text') {
            $parts[] = (string)($item['text'] ?? '');
        }
    }

    return implode("\n", $parts);
}

// A hard safety cap on the base64 image DATA itself (not the whole
// message), separate from TRANSCRIPT_BLOCK_HARD_CAP_LENGTH below (which
// only applies to text and would corrupt an image if it truncated
// mid-base64) - generous for a real screenshot (a few MB of actual image
// data), just a guard against something pathological blowing up the page.
const TRANSCRIPT_IMAGE_MAX_BASE64_LENGTH = 8_000_000;

/**
 * @param array<string, mixed> $block a raw {type: "image", source: {...}} block
 * @return array{media_type:string, data:string}|null
 */
function transcript_image_from_block(array $block): ?array
{
    $source = $block['source'] ?? null;

    if (!is_array($source) || ($source['type'] ?? null) !== 'base64') {
        return null;
    }

    $data = (string)($source['data'] ?? '');

    if ($data === '' || strlen($data) > TRANSCRIPT_IMAGE_MAX_BASE64_LENGTH) {
        return null;
    }

    return ['media_type' => (string)($source['media_type'] ?? 'image/png'), 'data' => $data];
}

/**
 * A tool_result's content can include an inline image alongside its text
 * (e.g. a browser-automation screenshot tool, verified against a real
 * capture) - the first one found, if any.
 *
 * @return array{media_type:string, data:string}|null
 */
function transcript_tool_result_image(mixed $content): ?array
{
    if (!is_array($content)) {
        return null;
    }

    foreach ($content as $item) {
        if (is_array($item) && ($item['type'] ?? null) === 'image') {
            $image = transcript_image_from_block($item);

            if ($image !== null) {
                return $image;
            }
        }
    }

    return null;
}

/**
 * Parses one JSONL line into a renderable transcript entry, or null for a
 * meta-only, malformed, or content-less line.
 *
 * @return array{type:string, role:?string, timestamp:?string, blocks:array<int, array{kind:string, text:string}>}|null
 */
function parse_transcript_line(string $line): ?array
{
    $decoded = json_decode($line, true);

    if (!is_array($decoded)) {
        return null;
    }

    $type = (string)($decoded['type'] ?? '');

    if ($type === '' || in_array($type, transcript_meta_only_types(), true)) {
        return null;
    }

    $message = $decoded['message'] ?? null;

    if (!is_array($message)) {
        return null;
    }

    $content = $message['content'] ?? null;
    $blocks = [];

    if (is_string($content) && $content !== '') {
        $blocks[] = ['kind' => 'text', 'text' => $content];
    } elseif (is_array($content)) {
        foreach ($content as $block) {
            if (is_array($block) && ($block['type'] ?? null) !== 'thinking') {
                $blocks[] = summarize_content_block($block);
            }
        }
    }

    // Thinking is never persisted as a chat entry, even a hidden one - a
    // message that was *only* thinking (no text/tool_use alongside it, the
    // common case: Claude Code writes it as its own separate JSONL line)
    // ends up with zero blocks here and is treated the same as a
    // meta-only line, not an empty bubble with a role header and nothing
    // in it. The live "is it thinking right now" state is a separate,
    // transient signal - see pane_title_is_working() in Sessions.php.
    if ($blocks === []) {
        return null;
    }

    foreach ($blocks as &$block) {
        if (strlen($block['text']) > TRANSCRIPT_BLOCK_HARD_CAP_LENGTH) {
            $block['text'] = substr($block['text'], 0, TRANSCRIPT_BLOCK_HARD_CAP_LENGTH) . "\n… (truncated)";
        }
    }
    unset($block);

    return [
        'type' => $type,
        'role' => is_string($message['role'] ?? null) ? $message['role'] : null,
        'timestamp' => is_string($decoded['timestamp'] ?? null) ? $decoded['timestamp'] : null,
        'blocks' => $blocks,
    ];
}

/**
 * Reads one page of renderable transcript entries, newest-first request /
 * oldest-first response (natural top-to-bottom reading order once
 * rendered). Walks backward from either the end of the file (no cursor)
 * or from just before line number $before - a 1-indexed raw line count,
 * stable as a cursor since Claude Code only ever appends to its own
 * transcript files. $limit counts renderable entries, not raw lines -
 * meta-only/content-less lines are skipped for free and don't count
 * against it, so a page always has up to $limit real entries regardless
 * of how many meta lines sit between them.
 *
 * @return array{ok:bool, entries:array<int, array>, next_before:?int, has_more:bool, message?:string}
 */
function read_transcript_page(string $path, ?int $before, int $limit): array
{
    $lines = @file($path, FILE_IGNORE_NEW_LINES);

    if ($lines === false) {
        return ['ok' => false, 'entries' => [], 'next_before' => null, 'has_more' => false, 'message' => 'Transcript file could not be read'];
    }

    $totalLines = count($lines);
    $upperBound = $before !== null ? max(0, min($before - 1, $totalLines)) : $totalLines; // exclusive, 0-indexed

    $entries = [];
    $index = $upperBound;

    while ($index > 0 && count($entries) < $limit) {
        $index--;
        $parsed = parse_transcript_line($lines[$index]);

        if ($parsed !== null) {
            $entries[] = $parsed + ['line' => $index + 1];
        }
    }

    $entries = array_reverse($entries);

    return [
        'ok' => true,
        'entries' => $entries,
        'next_before' => $index > 0 ? $index + 1 : null,
        'has_more' => $index > 0,
    ];
}
