<?php
declare(strict_types=1);

/**
 * Read-only access to Claude Code's own JSONL conversation transcripts
 * under ~/.claude/projects/<encoded-cwd>/<session-id>.jsonl - this file
 * never writes to them. Sessions created via create_cc_session() are
 * launched with an explicit --session-id (a UUID this app generates
 * itself, stored in the sidecar - see generate_uuid_v4() in Sessions.php),
 * so a transcript is found by globbing for that UUID's filename rather
 * than reimplementing Claude Code's own cwd -> directory-name encoding.
 */

function claude_projects_dir(): string
{
    return home_root() . '/.claude/projects';
}

/**
 * JSONL line types that carry no `message` payload (mode switches,
 * permission-mode changes, bridge/queue bookkeeping, file-history
 * snapshots, stop-hook summaries, ...) - skipped when rendering history.
 * Verified against a real, 700+-message transcript that none of these
 * (nor any other observed type) ever carry a `message` key, so
 * parse_transcript_line()'s own `!is_array($message)` check would filter
 * them out regardless - this list exists for clarity/intent, not as the
 * only thing standing between them and getting rendered as garbage.
 *
 * @return string[]
 */
function transcript_meta_only_types(): array
{
    return [
        'mode', 'permission-mode', 'bridge-session', 'last-prompt', 'attachment', 'ai-title',
        'system', 'queue-operation', 'file-history-snapshot', 'file-history-delta',
    ];
}

/**
 * Finds the transcript file for a session id generated by
 * generate_uuid_v4() - never trusts $claudeSessionId to already be safe,
 * since it ultimately traces back to a sidecar file, so it's validated as
 * UUID-shaped before touching the filesystem.
 */
function find_transcript_path(string $claudeSessionId): ?string
{
    if (preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i', $claudeSessionId) !== 1) {
        return null;
    }

    $matches = glob(claude_projects_dir() . '/*/' . $claudeSessionId . '.jsonl') ?: [];

    return $matches[0] ?? null;
}

const TRANSCRIPT_BLOCK_PREVIEW_LENGTH = 2000;

/**
 * @param array<string, mixed> $block
 * @return array{kind:string, text:string}
 */
function summarize_content_block(array $block): array
{
    $type = (string)($block['type'] ?? '');

    return match ($type) {
        'text' => ['kind' => 'text', 'text' => (string)($block['text'] ?? '')],
        'thinking' => ['kind' => 'thinking', 'text' => (string)($block['thinking'] ?? '')],
        'tool_use' => ['kind' => 'tool_use', 'text' => (string)($block['name'] ?? 'tool')],
        'tool_result' => ['kind' => 'tool_result', 'text' => transcript_tool_result_text($block['content'] ?? null)],
        default => ['kind' => $type !== '' ? $type : 'unknown', 'text' => ''],
    };
}

/**
 * A tool_result's `content` is either a plain string or a list of blocks
 * (usually just {type: "text", text: ...}) - flattened to plain text for
 * the history view, which only ever shows a preview, never the raw shape.
 */
function transcript_tool_result_text(mixed $content): string
{
    if (is_string($content)) {
        return $content;
    }

    if (!is_array($content)) {
        return '';
    }

    $parts = [];

    foreach ($content as $item) {
        if (is_array($item) && ($item['type'] ?? null) === 'text') {
            $parts[] = (string)($item['text'] ?? '');
        }
    }

    return implode("\n", $parts);
}

/**
 * Parses one JSONL line into a renderable transcript entry, or null for a
 * meta-only, malformed, or content-less line.
 *
 * @return array{type:string, role:?string, timestamp:?string, blocks:array<int, array{kind:string, text:string}>}|null
 */
function parse_transcript_line(string $line): ?array
{
    $decoded = json_decode($line, true);

    if (!is_array($decoded)) {
        return null;
    }

    $type = (string)($decoded['type'] ?? '');

    if ($type === '' || in_array($type, transcript_meta_only_types(), true)) {
        return null;
    }

    $message = $decoded['message'] ?? null;

    if (!is_array($message)) {
        return null;
    }

    $content = $message['content'] ?? null;
    $blocks = [];

    if (is_string($content) && $content !== '') {
        $blocks[] = ['kind' => 'text', 'text' => $content];
    } elseif (is_array($content)) {
        foreach ($content as $block) {
            if (is_array($block)) {
                $blocks[] = summarize_content_block($block);
            }
        }
    }

    if ($blocks === []) {
        return null;
    }

    foreach ($blocks as &$block) {
        if (strlen($block['text']) > TRANSCRIPT_BLOCK_PREVIEW_LENGTH) {
            $block['text'] = substr($block['text'], 0, TRANSCRIPT_BLOCK_PREVIEW_LENGTH) . "\n… (truncated)";
        }
    }
    unset($block);

    return [
        'type' => $type,
        'role' => is_string($message['role'] ?? null) ? $message['role'] : null,
        'timestamp' => is_string($decoded['timestamp'] ?? null) ? $decoded['timestamp'] : null,
        'blocks' => $blocks,
    ];
}

/**
 * Reads one page of renderable transcript entries, newest-first request /
 * oldest-first response (natural top-to-bottom reading order once
 * rendered). Walks backward from either the end of the file (no cursor)
 * or from just before line number $before - a 1-indexed raw line count,
 * stable as a cursor since Claude Code only ever appends to its own
 * transcript files. $limit counts renderable entries, not raw lines -
 * meta-only/content-less lines are skipped for free and don't count
 * against it, so a page always has up to $limit real entries regardless
 * of how many meta lines sit between them.
 *
 * @return array{ok:bool, entries:array<int, array>, next_before:?int, has_more:bool, message?:string}
 */
function read_transcript_page(string $path, ?int $before, int $limit): array
{
    $lines = @file($path, FILE_IGNORE_NEW_LINES);

    if ($lines === false) {
        return ['ok' => false, 'entries' => [], 'next_before' => null, 'has_more' => false, 'message' => 'Transcript file could not be read'];
    }

    $totalLines = count($lines);
    $upperBound = $before !== null ? max(0, min($before - 1, $totalLines)) : $totalLines; // exclusive, 0-indexed

    $entries = [];
    $index = $upperBound;

    while ($index > 0 && count($entries) < $limit) {
        $index--;
        $parsed = parse_transcript_line($lines[$index]);

        if ($parsed !== null) {
            $entries[] = $parsed + ['line' => $index + 1];
        }
    }

    $entries = array_reverse($entries);

    return [
        'ok' => true,
        'entries' => $entries,
        'next_before' => $index > 0 ? $index + 1 : null,
        'has_more' => $index > 0,
    ];
}
